// Assembles build/plugin-marketplace: one plugin marketplace for ChatGPT / Codex and Claude (Cowork and
// Claude Code) holding the AwardWallet plugin (plugin/ plus the bundled server). ChatGPT reads
// .agents/plugins/marketplace.json and the plugin's plugin.json + mcp.json; Claude reads
// .claude-plugin/marketplace.json and the plugin's .claude-plugin/plugin.json. The release workflow
// publishes it to the `plugin` branch; for local testing, add the folder itself. In ChatGPT the
// launchers in bin/ start the server with ChatGPT's own Node.js, so users don't have to install Node.
import { chmodSync, cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";

const pkg = JSON.parse(readFileSync("package.json", "utf8"));
const plugin = JSON.parse(readFileSync("plugin/plugin.json", "utf8"));
const mcp = JSON.parse(readFileSync("plugin/mcp.json", "utf8"));
const claude = JSON.parse(readFileSync("plugin/.claude-plugin/plugin.json", "utf8"));
for (const [file, manifest] of [["plugin/plugin.json", plugin], ["plugin/.claude-plugin/plugin.json", claude]]) {
  if (manifest.version !== pkg.version) throw new Error(`${file} version ${manifest.version} != package.json ${pkg.version}`);
}
if (claude.name !== plugin.name) throw new Error(`plugin names differ: ${plugin.name} (ChatGPT) vs ${claude.name} (Claude)`);
// The Claude marketplace on the default branch (claude.ai can't add a branch) points into the published one.
const rootEntry = JSON.parse(readFileSync(".claude-plugin/marketplace.json", "utf8")).plugins.find((p) => p.name === claude.name);
if (!rootEntry || rootEntry.source?.path !== `plugins/${claude.name}` || rootEntry.source?.ref !== "plugin") {
  throw new Error(`.claude-plugin/marketplace.json must list ${claude.name} at plugins/${claude.name} on the plugin branch`);
}
if (!existsSync("dist/awardwallet-mcp.mjs")) throw new Error("Build the server first (npm run build).");

// The checks a host would fail on silently: schema ids, the name, and every file the manifests point to.
const fail = (message) => {
  throw new Error(`plugin: ${message}`);
};
if (plugin.$schema !== "https://agent-plugins.org/schemas/1.0.0/plugin.schema.json") fail("plugin.json $schema");
if (mcp.$schema !== "https://agent-plugins.org/schemas/1.0.0/mcp.schema.json") fail("mcp.json $schema");
if (!/^(?!.*(?:--|\.\.))[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?$/.test(plugin.name)) fail(`invalid name ${plugin.name}`);
const ui = plugin.extensions?.["com.openai"] ?? {};
const referenced = [ui.interface?.composerIcon, ui.interface?.logo, ui.onboardingSkill, ...Object.values(mcp.mcpServers).map((s) => s.command)];
for (const path of referenced.filter(Boolean)) {
  if (!path.startsWith("./")) fail(`${path} must start with ./`);
  const file = `plugin/${path.slice(2)}`;
  if (!existsSync(file) && !existsSync(`${file}.cmd`)) fail(`${path} is missing`);
}
if ([ui.interface?.shortDescription, ui.interface?.displayName].some((text) => (text ?? "").length > 30)) fail("displayName and shortDescription must be 30 characters or fewer");

const root = "build/plugin-marketplace";
const dir = `${root}/plugins/${plugin.name}`;
rmSync(root, { recursive: true, force: true });
mkdirSync(`${root}/.agents/plugins`, { recursive: true });
mkdirSync(`${root}/.claude-plugin`, { recursive: true });
cpSync("plugin", dir, { recursive: true });
mkdirSync(`${dir}/server`, { recursive: true });
cpSync("dist/awardwallet-mcp.mjs", `${dir}/server/awardwallet-mcp.mjs`);

// Line endings and modes don't depend on the checkout: cmd.exe wants CRLF, sh wants LF and +x.
const launcher = `${dir}/bin/awardwallet-mcp`;
writeFileSync(launcher, readFileSync(launcher, "utf8").replace(/\r\n/g, "\n"));
chmodSync(launcher, 0o755);
writeFileSync(`${launcher}.cmd`, readFileSync(`${launcher}.cmd`, "utf8").replace(/\r?\n/g, "\r\n"));

const marketplace = {
  name: "awardwallet-mcp",
  interface: { displayName: "AwardWallet MCP" },
  plugins: [
    {
      name: plugin.name,
      source: { source: "local", path: `./plugins/${plugin.name}` },
      policy: { installation: "AVAILABLE", authentication: "ON_INSTALL" },
      category: ui.interface?.category ?? "Travel",
    },
  ],
};
writeFileSync(`${root}/.agents/plugins/marketplace.json`, `${JSON.stringify(marketplace, null, 2)}\n`);
const claudeMarketplace = {
  name: marketplace.name,
  owner: { name: claude.author.name, url: claude.author.url },
  description: "AwardWallet MCP plugin (unofficial)",
  plugins: [{ name: claude.name, source: `./plugins/${claude.name}`, description: claude.description, category: "travel" }],
};
writeFileSync(`${root}/.claude-plugin/marketplace.json`, `${JSON.stringify(claudeMarketplace, null, 2)}\n`);
// Keep git from rewriting line endings when this folder is published as a branch.
writeFileSync(`${root}/.gitattributes`, "* -text\n");
writeFileSync(
  `${root}/README.md`,
  `# AwardWallet plugin for ChatGPT, Codex and Claude (v${pkg.version})

Generated by the release workflow of ${pkg.homepage.replace(/#.*$/, "")}; don't edit this branch by hand.
See that README for setup instructions.
`,
);
console.log(`Built ${root} (plugin ${plugin.name} v${plugin.version})`);
