// Assembles build/chatgpt-marketplace: a plugin marketplace for ChatGPT desktop and Codex holding the
// AwardWallet plugin (chatgpt-plugin/ plus the bundled server). The release workflow publishes it to
// the chatgpt-plugin branch, which users add with `codex plugin marketplace add`; for local testing,
// add the folder itself. The launchers in bin/ start the server with the Node.js runtime that ships
// with ChatGPT, so users don't have to install Node.
import { chmodSync, cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";

const pkg = JSON.parse(readFileSync("package.json", "utf8"));
const plugin = JSON.parse(readFileSync("chatgpt-plugin/plugin.json", "utf8"));
const mcp = JSON.parse(readFileSync("chatgpt-plugin/mcp.json", "utf8"));
if (plugin.version !== pkg.version) throw new Error(`chatgpt-plugin/plugin.json version ${plugin.version} != package.json ${pkg.version}`);
if (!existsSync("dist/awardwallet-mcp.mjs")) throw new Error("Build the server first (npm run build).");

// The checks a host would fail on silently: schema ids, the name, and every file the manifests point to.
const fail = (message) => {
  throw new Error(`chatgpt-plugin: ${message}`);
};
if (plugin.$schema !== "https://agent-plugins.org/schemas/1.0.0/plugin.schema.json") fail("plugin.json $schema");
if (mcp.$schema !== "https://agent-plugins.org/schemas/1.0.0/mcp.schema.json") fail("mcp.json $schema");
if (!/^(?!.*(?:--|\.\.))[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?$/.test(plugin.name)) fail(`invalid name ${plugin.name}`);
const ui = plugin.extensions?.["com.openai"] ?? {};
const referenced = [ui.interface?.composerIcon, ui.interface?.logo, ui.onboardingSkill, ...Object.values(mcp.mcpServers).map((s) => s.command)];
for (const path of referenced.filter(Boolean)) {
  if (!path.startsWith("./")) fail(`${path} must start with ./`);
  const file = `chatgpt-plugin/${path.slice(2)}`;
  if (!existsSync(file) && !existsSync(`${file}.cmd`)) fail(`${path} is missing`);
}
if ([ui.interface?.shortDescription, ui.interface?.displayName].some((text) => (text ?? "").length > 30)) fail("displayName and shortDescription must be 30 characters or fewer");

const root = "build/chatgpt-marketplace";
const dir = `${root}/plugins/${plugin.name}`;
rmSync(root, { recursive: true, force: true });
mkdirSync(`${root}/.agents/plugins`, { recursive: true });
cpSync("chatgpt-plugin", dir, { recursive: true });
mkdirSync(`${dir}/server`, { recursive: true });
cpSync("dist/awardwallet-mcp.mjs", `${dir}/server/awardwallet-mcp.mjs`);

// Line endings and modes don't depend on the checkout: cmd.exe wants CRLF, sh wants LF and +x.
const launcher = `${dir}/bin/awardwallet-mcp`;
writeFileSync(launcher, readFileSync(launcher, "utf8").replace(/\r\n/g, "\n"));
chmodSync(launcher, 0o755);
writeFileSync(`${launcher}.cmd`, readFileSync(`${launcher}.cmd`, "utf8").replace(/\r?\n/g, "\r\n"));

const marketplace = {
  name: "awardwallet-mcp",
  interface: { displayName: "AwardWallet MCP" },
  plugins: [
    {
      name: plugin.name,
      source: { source: "local", path: `./plugins/${plugin.name}` },
      policy: { installation: "AVAILABLE", authentication: "ON_INSTALL" },
      category: ui.interface?.category ?? "Travel",
    },
  ],
};
writeFileSync(`${root}/.agents/plugins/marketplace.json`, `${JSON.stringify(marketplace, null, 2)}\n`);
// Keep git from rewriting line endings when this folder is published as a branch.
writeFileSync(`${root}/.gitattributes`, "* -text\n");
writeFileSync(
  `${root}/README.md`,
  `# AwardWallet plugin for ChatGPT and Codex (v${pkg.version})

Generated by the release workflow of ${pkg.homepage.replace(/#.*$/, "")}; don't edit this branch by hand.
See that README for setup instructions.
`,
);
console.log(`Built ${root} (plugin ${plugin.name} v${plugin.version})`);
